## Deployment da aplicação Node JS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversor
        image: dlpires300/conversao-temperatura:v1
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        resources:
          limits:
            cpu: "0.2"
            memory: "32Mi"
          requests:
            cpu: "0.1"
            memory: "24Mi"

---
## Services da aplicação NodeJS
apiVersion: v1
kind: Service
metadata:
  name: conversor
spec:
  selector:
    app: conversor
  ports:
  - port: 80
    targetPort: 8080
  #type: LoadBalancer
    nodePort: 30000
  type: NodePort
